apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

helmCharts:
  - name: helloworld
    releaseName: helloworld
    valuesFile: helloworld.yaml

helmGlobals:
   chartHome: ../charts
  
