apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginxnp
  name: nginxnp
spec:
  ports:
  - name: 80-80
    nodePort: 32000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
status:
  loadBalancer: {}
