apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
   name: beehives.singleton.dev  # must be <plural>.<group>
spec:
   group: singleton.dev
   names:
     plural:  beehives  # this allow to do a kubectl get beehives
     singular:  beehive  # this allow to do a kubectl get beehive
     kind: BeeHive # this is the custom resource kind to put in its yaml file
     shortNames:   # Alternatives short names
     -  hive
   scope: Namespaced # is not cluster wide but namespaced
   versions:  # check this out   (https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#specify-multiple-versions)
   - name: v1
     served: true
     storage: true
     schema:  # define the datafield available for the custom object
       openAPIV3Schema:
         type: object
         properties:
            spec:
              type: object
              properties:
                 supers:
                   type: integer
                 bees:
                   type: integer
