
# Kubernetes start first the init container
# Once the web httpd init container is started we start alpine
kind: Pod
apiVersion: v1
metadata:
  name: init-example1
spec:
  initContainers:
  - name: web
    image: httpd
  containers:
  - name: alpine
    image: alpine
