---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-repo-pv
  namespace: docker-registry
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /var/lib/docker-registry/repository
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-repo-pvc
  namespace: docker-registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
