kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
      resolve_timeout:  1m
    templates:
    - '/etc/alertmanager-templates/*.tmpl'

    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 30m
      receiver: team-X-sms-web-hook

      routes:
      - receiver: team-X-sms-web-hook

    receivers:
      - name: team-X-sms-web-hook
        webhook_configs:
        - url: "http://sms-sender.monitoring.svc.cluster.local:9088/send"

    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'dev', 'instance']
