apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mypod-rolebinding
  namespace: default
roleRef:
  kind: Role
  name: mypod-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: mypod-sa
    namespace: default
