apiVersion: v1
kind: Pod
metadata:
  name: new-mypod
  namespace: ckad
spec:
  serviceAccountName: mypod-sa
  containers:
  - name: new-mybod
    image: radial/busyboxplus
    command:
    - sleep
    - "3600"
