apiVersion: v1
kind: Pod
metadata:
  name : probe-test-ready
  namespace: default
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - sleep
      - "3600"
    readinessProbe:
      periodSeconds: 5
      exec:
        command:
          - cat
          - /tmp/noexistsfile
