apiVersion: v1
kind: Pod
metadata:
  name : probe-test-ready-httpget
  namespace: default
spec:
  containers:
  - name: nginx-probe
    image: nginx
    ports:
        - containerPort: 80
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
      httpGet:
        path: /
        port: 80
