apiVersion: v1
kind: Pod
metadata:
  name : probe-test-ready-tcpsocket
  namespace: default
spec:
  containers:
  - name: nginx-probe
    image: nginx
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
      tcpSocket:
        port: 80

