---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: sandbox
spec:
  replicas: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
