apiVersion: v1
kind: Pod
metadata:
  name: nginx4
  namespace: limited-ns
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
       requests:
         cpu: 1
         memory: 200M
       limits:
         cpu:  2
         memory: 400M
