apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  namespace: limited-ns
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
       requests:
         cpu: 0.5
         memory: 200M
       limits:
         cpu:  1
         memory: 400M
