apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: alertmanager-templates
  namespace: monitoring
data:
  my_custom_email.tmpl: |
    {{ define "custom_mail_subject" }}Alert on {{ range .Alerts.Firing }}{{ .Labels.instance }} {{ end }}{{ end }}
    {{ define "custom_mail_html" }}
    <html>
    <head>
    <title>Alert!</title>
    </head>
    <body>
    {{ range .Alerts.Firing }}

    <p>{{ .Labels.alertname }} on {{ .Labels.instance }}<br/>
    {{ if ne .Annotations.summary "" }}{{ .Annotations.summary }}{{ end }}</p>
    
    <p>Details:</p>
    
    <p>
    {{ range .Annotations.SortedPairs }}
      {{ .Name }} = {{ .Value }}<br/>
    {{ end }}
    </p>
    
    <p>
    {{ range .Labels.SortedPairs }}
      {{ .Name }} = {{ .Value }}<br/>
    {{ end }}
    </p>
    
    {{ end }}
    
    </body></html>
    {{ end }}
