kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager-templates/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname']
      group_wait: 10s
      repeat_interval: 30m
    receivers:
    - name: alert-emailer
      email_configs:
      - to: giacomini.corrado@free.fr
        from: corrado.giacomini@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: 'corrado.giacomini@gmail.com'
        auth_identity: 'corrado.giacomini@gmail.com'
        auth_password: '+Ncc1701d+'
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'dev', 'instance']




