# POD running nginx web server exposing port 80
---
apiVersion: v1
kind: Pod
metadata:
   name: ambassador-test-webserver
   namespace: ckad
   labels:
     app: ambassador-test
spec:
   containers:
   - name: nginx
     image: nginx:stable
     ports:
     - containerPort: 80

# Service to access the above POD exposing port 8081 and targeting 80
---
apiVersion: v1
kind: Service
metadata:
   name: ambassador-test-svc
   namespace: ckad
spec:
   selector:
     app: ambassador-test
   ports:
   - protocol: TCP
     port: 8081
     targetPort: 80
