apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: example-001
    app.kubernetes.io/name: example-001
  name: example-001
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: example-001
      app.kubernetes.io/name: example-001
  template:
    metadata:
      labels:
        app.kubernetes.io/component: example-001
        app.kubernetes.io/name: example-001
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Equal
        effect: NoSchedule
      imagePullSecrets:
      - name: centos8s-server-secret
      containers:
      - name: example-001
        image: centos8s-server.singleton.net:443/example-001:latest
        ports:
          - containerPort: 8000
            name: metrics
            protocol: TCP
          - containerPort: 8001
            name: web
            protocol: TCP

