apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-12-08T14:21:03Z"
  labels:
    run: curl
  name: curl
  namespace: training
  resourceVersion: "526495"
  uid: e3ced772-45e3-43c2-81ee-9bfdb6897cd7
spec:
  containers:
  - image: radial/busyboxplus:curl
    imagePullPolicy: IfNotPresent
    name: curl
    resources: {}
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-bxxsc
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8s-node2.singleton.net
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-bxxsc
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-12-08T14:21:03Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-12-08T14:22:29Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-12-08T14:22:29Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-12-08T14:21:03Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://cf1bf914aff7e7fec33c6b7418e68f2b35b2b0713252d2c39dcf65c3426248c3
    image: radial/busyboxplus:curl
    imageID: docker-pullable://radial/busyboxplus@sha256:a68c05ab1112fd90ad7b14985a48520e9d26dbbe00cb9c09aa79fdc0ef46b372
    lastState:
      terminated:
        containerID: docker://4e239db789dcf06d1260031964ddc54ad321f4a198e03dca44d5c15c46196a80
        exitCode: 0
        finishedAt: "2021-12-08T14:22:27Z"
        reason: Completed
        startedAt: "2021-12-08T14:21:04Z"
    name: curl
    ready: true
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2021-12-08T14:22:28Z"
  hostIP: 192.168.56.12
  phase: Running
  podIP: 10.36.0.0
  podIPs:
  - ip: 10.36.0.0
  qosClass: BestEffort
  startTime: "2021-12-08T14:21:03Z"
