apiVersion: v1
kind: Service
metadata:
  name: sidecar-svc-headless
spec:
  clusterIP: None
  selector:
    app: sidecar
  ports:
  - port: 8080
    name: http-port
    targetPort: 80
  type: ClusterIP
