apiVersion: v1
kind: Pod
metadata:
  name:  secret-pod-example
spec:
  containers:
  - name: pod-example
    image: k8s.gcr.io/busybox
    command: [ "/bin/sh", "-c", "watch -n 5 ls /etc/config/"]
    volumeMounts:
    - name: secret
      mountPath: /etc/config
  volumes:
  - name: secret
    secret:
       secretName: secret-example
