apiVersion: v1
kind: Pod
metadata:
  name:  secret-pod-example2
spec:
  containers:
  - name: pod-example
    image: k8s.gcr.io/busybox
    command: [ "/bin/sh", "-c", "watch -n 5 echo $MY_ENV_PASSWORD"]
    env:
    - name: MY_ENV_PASSWORD
      valueFrom:
        secretKeyRef: 
          name: my-new-secret
          key: password
