apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mars
  name: mars
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mars
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mars
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
