apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: saturn
  name: saturn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saturn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: saturn
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
