---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment # Name of the deployment to update
  namespace: sandbox
spec:
  template:
    spec:
      containers:
      - name: my-container
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "500Mi"
            cpu: "500m"
