apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: example-001v1
    app.kubernetes.io/name: example-001v1
  name: example-001v1
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: example-001v1
      app.kubernetes.io/name: example-001v1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: example-001v1
        app.kubernetes.io/name: example-001v1
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Equal
        effect: NoSchedule
      imagePullSecrets:
      - name: centos8s-server-secret
      containers:
      - name: example-001v1
        imagePullPolicy: Always
        image: centos8s-server.singleton.net:443/example-001:v1
        ports:
          - containerPort: 8000
            name: metrics
            protocol: TCP
          - containerPort: 8001
            name: web
            protocol: TCP

