apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-2
spec:
  containers:
  - name: demo-pod-2
    image: cirros
    command: ["/bin/sh", "-c", "watch -n 5 env"]
    env:
      - name: TRUCK
        valueFrom:
          configMapKeyRef:
            name: literals
            key: TRUCK
