apiVersion: v1
kind: Pod
metadata:
  name: cm-example-pod
spec:
  containers:
  - name: cm-example
    image: k8s.gcr.io/busybox
    command: [ "/bin/sh", "-c", "watch -n 5 ls /etc/config/"]
    volumeMounts:
    - name: conf
      mountPath: /etc/config
  volumes:
  - name: conf
    configMap:
      name:  cm-example
      items:
      - key: 002-cm-example.conf
        path: default.conf
