apiVersion: v1
kind: Pod
metadata:
  name: secret-app
spec:
  containers:
  - name: secret-app
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    resources:
      requests:
        memory: "64Mi"
      limits:
        memory: "128Mi"
  restartPolicy: OnFailure

