apiVersion: v1
kind: Pod
metadata:
  name: data-secret-pod
spec:
  containers:
  - name: secret-pod
    image: k8s.gcr.io/busybox
    command: [ "sh", "-c", "watch -n 5 ls /etc/config/"]
    volumeMounts:
    - name: conf
      mountPath: /etc/config
  volumes:
  - name: conf
    secret:
      secretName: data-secret
